### ISSUE TITLE
Component breaks with empty set

### ISSUE THREAD

**Issue by dphaener** [Legitcode/table#3]
The component won't render at all if it is passed an empty array.

**Comment by zackify** [comment]
Well it's not supposed to render anything if there's no data. Possibly
adding a message would be nice though.

**Comment by dphaener** [comment]
It breaks in the <Head /> component. I'm working on a fix right now. I think just rendering an empty table is fine. I'll have a PR up in a few. Just writing a few tests.

**Comment by zackify** [comment]
Oh o see. Makes sense.
