### ISSUE TITLE
why use <table> if it is discourage?

### ISSUE THREAD

**Issue by vasco3** [Legitcode/table#5]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table says 

Prior to the creation of CSS, HTML <table> elements were often used as a method for page layout. This usage has been discouraged since HTML 4, and the <table> element should not be used for layout purposes. However, HTML emails are an exception, where tables are still commonly used for layout purposes.

**Comment by dphaener** [comment]
I suppose it's being used for layout, but the idea is to present data in a tabular fashion. The idea is not necessarily to use this table for an entire page layout. If you are trying to present data as a "table", I don't see the use in trying to re-invent the wheel and lay it all out with additional markup. 

This is intended as a way to present data only, not for anything beyond that. 

@zackify Thoughts?

**Comment by kenwheeler** [comment]
I don't think that's entirely accurate. The use of tables as _layout_ elements has been discouraged, however for tabular data, it still remains very much a idiomatic and semantic choice. tldr: `<table>` should be used for tables.

**Comment by dphaener** [comment]
@kenwheeler :+1:  Agreed.

**Comment by vasco3** [comment]
what about responsive design? Would be hard to transform a from table in
desktop view into a card on mobile.
tables make add additional complexity to styling. And they add way too much
markup.

**Comment by kenwheeler** [comment]
You can use CSS to display table elements as `block` on mobile, while retaining their semantic value.
